class User < ActiveRecord::Base
  # extends ...................................................................
  # includes ..................................................................
  # security (i.e. attr_accessible) ...........................................
  # relationships .............................................................
  has_many :api_keys, as: :tokenable 

  # validations ...............................................................
  validates :email, uniqueness: true, format: { with: /.+@.+\..+/ }
  validates :name, presence: true
  validates :password, :confirmation => true, :length => {:within => 6..40}, on: :create

  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  has_secure_password

  # class methods .............................................................
  # public instance methods ...................................................

  def session_api_key
    api_keys.active.session.create
  end

  def clear_expired_api_keys
    api_keys.expired.destroy_all
  end
  
  # protected instance methods ................................................
  # private instance methods ..................................................
end
